---
collections:
    # Forked community.zabbix v1.8.0: fixed Bug #810
  - name: git+https://github.com/uscr/community.zabbix.git
    version: 1.8.1
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 3.7.0
roles:
  - name: geerlingguy.mysql
    version: 4.1.0
